app.articles:
    resource: "@AppBundle/Controller/ArticleController.php"
    type: annotation
    prefix: /articles

app.tags:
    resource: "@AppBundle/Controller/TagController.php"
    type: annotation
    prefix: /tags

tuser:
    resource: "@TUserBundle/Resources/config/routing.yml"