security:
    encoders:
        AppBundle\Entity\User: bcrypt

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]

    providers:
        db_users:
            entity:
                class: AppBundle:User

    firewalls:
        main:
            pattern:   ^/
            anonymous: ~
            form_login:
                login_path: app_security_login
                check_path: app_security_check
                csrf_provider: security.csrf.token_manager
            logout:
                path: app_security_logout
                target: /

    access_control:
#        - { path: ^/update, roles: ROLE_ADMIN  }
#        - { path: ^/remove, roles: ROLE_ADMIN  }