# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    # Custom data_collector to use our own template
    app.data_collector.translation:
        class: 'Symfony\Component\Translation\DataCollector\TranslationDataCollector'
        arguments: ['@translator.data_collector']
        tags:
            - { name: 'data_collector', template: "profiler/translation.html.twig", id: "translation", priority: 200 }