parameters:

services:
    trascastro.tuser.doctrine.userListener:
        class: Trascastro\TUserBundle\Doctrine\UserListener
        arguments: [@security.encoder_factory]
        tags:
            - { name: doctrine.event_listener, event: prePersist }

