<?php

namespace AppBundle\Entity;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllArticles()
    {
        $qb = $this->createQueryBuilder('a')
            ->addOrderBy('a.title', 'DESC')
            ->leftJoin('a.tags', 'tags')
            ->addSelect('tags')
            ->getQuery()
        ;

        return $qb->execute();
    }
}
