<?php

namespace AppBundle\Entity;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends \Doctrine\ORM\EntityRepository
{
    public function addTagsIfAreNew(Article $article)
    {
        $submitedTags = $article->getNewTags();
        preg_replace('/\s+/', ' ', $submitedTags);
        $tagsArray = explode(';', $submitedTags);

        foreach($tagsArray as $tagText) {
            if ($tagText) {
                $tag = $this->findOneByName($tagText);

                if (!$tag) {
                    $newTag = new Tag();
                    $newTag->setName($tagText);
                    $article->addTag($newTag);
                }
            }
        }
    }

    public function findAllTags()
    {
        $qb = $this->createQueryBuilder('tag')
            ->addOrderBy('tag.name', 'DESC')
            ->leftJoin('tag.articles', 'articles')
            ->addSelect('articles')
            ->getQuery();

        return $qb->execute();
    }
}
